include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

  errors:
    missing_return: error
    missing_required_param: error
    must_be_immutable: error
    sort_unnamed_constructors_first: ignore
    sort_pub_dependencies: ignore

linter:
  rules:
    - avoid_relative_lib_imports
    - prefer_relative_imports
    - prefer_const_declarations